### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by patroza** [deepsweet/typeon#1]
The compiler checks at compile time  and the json parsing happens at runtime, so according to the compiler, the type returned from parse is the union type json value, and not json map.
Also the compiler in the editor won't magically understand which keys and values exist in the json, nor know their type. The tests also only prove that json can get serialized and deserialezed.

**Comment by deepsweet** [comment]
Hi.

In my case I have a JSON based protocol, so things are serialized and then parsed back. There is a `params` field which is a pretty arbitrary JSON, so it's not really possible to type it properly, so first I put `{ [key: string]: any }` for it, and then made `typeon`, because I want to be sure that params are serializable and I didn't put anything wrong in there.

>type returned from parse is the union type json value, and not json map

Unfortunately that's how it works: `JSON.parse(1)`, `JSON.parse([])` and so on.

>The tests also only prove that json can get serialized and deserialezed.

I've tried (not really successfully) and want to try again https://github.com/Microsoft/dtslint for the sake of `// $ExpectError`, because I don't see a lot of sense only in positive tests for types. Maybe you have any suggestions on how to write tests in this situation?

**Comment by deepsweet** [comment]
Also I have this:

```
type TStringifiableFunction = (...args: TJsonValue[]) => TJsonValue
```

for functions which are going to be evaluated (not by me) later, after I passed them in with `myFn.toString()` to make sure that it's only possible to pass "simple" functions. Think of Puppeteer's [`page.evaluate`](https://github.com/GoogleChrome/puppeteer/blob/v1.6.2/docs/api.md#pageevaluatepagefunction-args).

**Comment by deepsweet** [comment]
https://github.com/deepsweet/typeon/issues/2
